site:
  title: SmartSE Usecase Cluster Documentation
  url: https://example.org/smartse-docs
  start_page: smartse-cluster::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
